// packages/solid/src/index.ts
// ============================================================================
// @kayforms/solid — Solid JS Adapter
// ============================================================================
// Bridges Kayforms reactive signals to Solid's reactive Signal/Context systems.
// ============================================================================

import {
  createSignal,
  onCleanup,
  createContext,
  useContext,
  type JSX,
  type Accessor,
} from "solid-js";
import {
  createForm,
  type FormConfig,
  type FormStore,
  type FormErrors,
  type FieldNode,
  type Signal,
  type Computed,
} from "@kayforms/core";

// ---------------------------------------------------------------------------
// Signal → Solid Accessor bridge
// ---------------------------------------------------------------------------

/**
 * Hook to convert a Kayforms Signal or Computed into a Solid read-only Accessor.
 * Automatically handles subscriptions and cleanups on component teardown.
 */
export function useSignalValue<T>(signal: Signal<T> | Computed<T>): Accessor<T> {
  const [val, setVal] = createSignal<T>(signal.peek());
  const unsubscribe = signal.subscribe((next) => {
    setVal(() => next);
  });
  onCleanup(unsubscribe);
  return val;
}

// ---------------------------------------------------------------------------
// Context System
// ---------------------------------------------------------------------------

const FormContext = createContext<FormStore<any>>();

export interface FormProviderProps {
  form: FormStore<any>;
  children: JSX.Element;
}

/** Provides form context to child Solid components */
export function FormProvider(props: FormProviderProps) {
  return FormContext.Provider({
    value: props.form,
    get children() {
      return props.children;
    },
  });
}

/** Injects form context into child Solid components */
export function useFormContext(): FormStore<any> {
  const store = useContext(FormContext);
  if (!store) {
    throw new Error(
      "[kayforms/solid] useField must be used inside a <FormProvider> component."
    );
  }
  return store;
}

// ---------------------------------------------------------------------------
// useForm
// ---------------------------------------------------------------------------

export interface UseFormReturn<T extends Record<string, unknown>> {
  /** The reactive form store */
  store: FormStore<T>;
  /** Solid Accessor for values */
  values: Accessor<T>;
  /** Solid Accessor for errors */
  errors: Accessor<FormErrors<T>>;
  /** Solid Accessor for dirty state */
  dirty: Accessor<boolean>;
  /** Solid Accessor for validity */
  valid: Accessor<boolean>;
  /** Solid Accessor for submitting state */
  submitting: Accessor<boolean>;
  /** Solid Accessor for validating state */
  validating: Accessor<boolean>;
  /** Submission handler */
  handleSubmit: (e?: Event) => void;
  /** Reset form values */
  reset: (values?: Partial<T>) => void;
  /** Get a field node by path */
  getField: <V = unknown>(path: string) => FieldNode<V>;
}

/**
 * Create and manage a Kayforms form in a Solid JS component.
 */
export function useForm<T extends Record<string, unknown>>(
  config: FormConfig<T>
): UseFormReturn<T> {
  const store = createForm(config);

  onCleanup(() => {
    store.dispose();
  });

  const values = useSignalValue(store.values);
  const errors = useSignalValue(store.errors);
  const dirty = useSignalValue(store.dirty);
  const valid = useSignalValue(store.valid);
  const submitting = useSignalValue(store.submitting);
  const validating = useSignalValue(store.validating);

  const handleSubmit = (e?: Event) => {
    e?.preventDefault();
    store.submit();
  };

  const reset = (newValues?: Partial<T>) => {
    store.reset(newValues);
  };

  return {
    store,
    values,
    errors,
    dirty,
    valid,
    submitting,
    validating,
    handleSubmit,
    reset,
    getField: store.getField,
  };
}

// ---------------------------------------------------------------------------
// useField
// ---------------------------------------------------------------------------

export interface UseFieldReturn<V = unknown> {
  /** Solid Accessor for field value */
  value: Accessor<V>;
  /** Solid Accessor for field error */
  error: Accessor<string | undefined>;
  /** Solid Accessor for touched state */
  touched: Accessor<boolean>;
  /** Solid Accessor for dirty state */
  dirty: Accessor<boolean>;
  /** Solid Accessor for validating state */
  validating: Accessor<boolean>;
  /** Triggered value update */
  onChange: (value: V) => void;
  /** Blur handler */
  onBlur: () => void;
  /** Props for binding to plain DOM inputs */
  inputProps: {
    value: V;
    onInput: (e: any) => void;
    onBlur: () => void;
  };
}

/**
 * Bind a single field's reactive signals in a Solid JS component.
 */
export function useField<V = unknown>(path: string): UseFieldReturn<V> {
  const store = useFormContext();
  const field = store.getField<V>(path);

  const value = useSignalValue(field.value);
  const error = useSignalValue(field.error);
  const touched = useSignalValue(field.touched);
  const dirty = useSignalValue(field.dirty);
  const validating = useSignalValue(field.validating);

  const onChange = (v: V) => field.onChange(v);
  const onBlur = () => field.onBlur();

  const handleInput = (e: any) => {
    field.onChange(e.target.value as V);
  };

  return {
    value,
    error,
    touched,
    dirty,
    validating,
    onChange,
    onBlur,
    get inputProps() {
      return {
        value: value(),
        onInput: handleInput,
        onBlur,
      };
    },
  };
}

// packages/angular/src/index.ts
// ============================================================================
// @kayforms/angular — Angular Signals Adapter
// ============================================================================
// Bridges Kayforms signals to Angular core Signals.
// Uses DestroyRef for clean, automatic subscription teardown.
// ============================================================================

import {
  signal as angularSignal,
  inject,
  DestroyRef,
  type Signal as AngularSignal,
} from "@angular/core";
import {
  createForm,
  type FormConfig,
  type FormStore,
  type FormErrors,
  type FieldNode,
  type Signal as KaySignal,
  type Computed as KayComputed,
} from "@kayforms/core";

// ---------------------------------------------------------------------------
// Signal → Angular Signal bridge
// ---------------------------------------------------------------------------

/**
 * Wrap a Kayforms Signal or Computed in an Angular core Signal.
 * Automatically unsubscribes when the host context is destroyed (via DestroyRef).
 */
export function toAngularSignal<T>(
  signal: KaySignal<T> | KayComputed<T>
): AngularSignal<T> {
  const angSig = angularSignal<T>(signal.peek());

  const unsubscribe = signal.subscribe((next) => {
    angSig.set(next);
  });

  // Automatically unsubscribe if running in an active Angular injection context
  try {
    const destroyRef = inject(DestroyRef);
    destroyRef.onDestroy(() => {
      unsubscribe();
    });
  } catch (err) {
    // Silent catch if called outside an injection context (e.g. manually managed)
  }

  // Return a read-only view of the Angular Signal
  return angSig.asReadonly();
}

// ---------------------------------------------------------------------------
// createAngularForm
// ---------------------------------------------------------------------------

export interface AngularFormReturn<T extends Record<string, unknown>> {
  /** Underlying Kayforms form store */
  store: FormStore<T>;
  /** Angular Signal for values */
  values: AngularSignal<T>;
  /** Angular Signal for errors */
  errors: AngularSignal<FormErrors<T>>;
  /** Angular Signal for dirty state */
  dirty: AngularSignal<boolean>;
  /** Angular Signal for validity */
  valid: AngularSignal<boolean>;
  /** Angular Signal for submitting state */
  submitting: AngularSignal<boolean>;
  /** Angular Signal for validating state */
  validating: AngularSignal<boolean>;
  /** Submission wrapper */
  handleSubmit: (e?: Event) => void;
  /** Reset helper */
  reset: (values?: Partial<T>) => void;
  /** Get a field node by path */
  getField: <V = unknown>(path: string) => FieldNode<V>;
}

/**
 * Create and manage a Kayforms form in an Angular component or service.
 * Registers auto-dispose of the store and subscriptions on DestroyRef trigger.
 */
export function createAngularForm<T extends Record<string, unknown>>(
  config: FormConfig<T>
): AngularFormReturn<T> {
  const store = createForm(config);

  try {
    const destroyRef = inject(DestroyRef);
    destroyRef.onDestroy(() => {
      store.dispose();
    });
  } catch (err) {
    // Silent catch if called outside injection context
  }

  const values = toAngularSignal(store.values);
  const errors = toAngularSignal(store.errors);
  const dirty = toAngularSignal(store.dirty);
  const valid = toAngularSignal(store.valid);
  const submitting = toAngularSignal(store.submitting);
  const validating = toAngularSignal(store.validating);

  const handleSubmit = (e?: Event) => {
    e?.preventDefault();
    store.submit();
  };

  const reset = (newValues?: Partial<T>) => {
    store.reset(newValues);
  };

  return {
    store,
    values,
    errors,
    dirty,
    valid,
    submitting,
    validating,
    handleSubmit,
    reset,
    getField: store.getField,
  };
}

// ---------------------------------------------------------------------------
// createAngularField
// ---------------------------------------------------------------------------

export interface AngularFieldReturn<V = unknown> {
  /** Underlying FieldNode */
  field: FieldNode<V>;
  /** Angular Signal for value */
  value: AngularSignal<V>;
  /** Angular Signal for error */
  error: AngularSignal<string | undefined>;
  /** Angular Signal for touched state */
  touched: AngularSignal<boolean>;
  /** Angular Signal for dirty state */
  dirty: AngularSignal<boolean>;
  /** Angular Signal for validating state */
  validating: AngularSignal<boolean>;
  /** Triggered value update */
  onChange: (value: V) => void;
  /** Blur handler */
  onBlur: () => void;
  /** Props for binding to plain DOM inputs */
  inputProps: {
    value: V;
    onInput: (e: any) => void;
    onBlur: () => void;
  };
}

/**
 * Bind a single field's reactive signals in an Angular component or directive.
 */
export function createAngularField<V = unknown>(
  store: FormStore<any>,
  path: string
): AngularFieldReturn<V> {
  const field = store.getField<V>(path);

  const value = toAngularSignal(field.value);
  const error = toAngularSignal(field.error);
  const touched = toAngularSignal(field.touched);
  const dirty = toAngularSignal(field.dirty);
  const validating = toAngularSignal(field.validating);

  const onChange = (v: V) => field.onChange(v);
  const onBlur = () => field.onBlur();

  const handleInput = (e: any) => {
    field.onChange(e.target.value as V);
  };

  return {
    field,
    value,
    error,
    touched,
    dirty,
    validating,
    onChange,
    onBlur,
    get inputProps() {
      return {
        value: field.value.peek(),
        onInput: handleInput,
        onBlur,
      };
    },
  };
}
